language: java
jdk:
  - openjdk7
  - oraclejdk7  
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'angular-spring-demo' ]; then cd .. && eval "mv $currentfolder angular-spring-demo" && cd angular-spring-demo; fi
  - npm install -g bower grunt-cli grunt
  - bower install && npm install && grunt
